class ClassesStudentsController:
    def __init__(self, db, SQLFORM):
        self.db = db
        self.SQLFORM = SQLFORM

    def index(self):        
        """
        This function generates the index page for the application.

        Parameters:
            None

        Returns:
            dict: A dictionary containing the 'grid' object generated by the SQLFORM.grid function.
        """
        grid = self.SQLFORM.grid(
            self.db.classes_students,
            create=True,
            editable=True,
            deletable=True,
            details=True,
            user_signature=False
        )
        return dict(grid=grid)