class SchedulesController:
    def __init__(self, db, SQLFORM):
        self.db = db
        self.SQLFORM = SQLFORM
    
    def index(self):
        """
        Return a dictionary containing the grid object generated by the SQLFORM.grid function.

        Parameters:
            None

        Returns:
            dict: A dictionary containing the grid object.

        Example usage:
            grid = self.index()
        """
        grid = self.SQLFORM.grid(
            self.db.schedules,
            create=True,
            editable=True,
            deletable=True,
            details=True,
            user_signature=False
        )
        return dict(grid=grid)