version: '3.8'

services:
  web:
    image: anyel/sip_web2py:v1.0
    ports:
      - "8000:8000"
    build: .
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASS
      POSTGRES_DB: sip_ingenieria
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - web

volumes:
  postgres_data:
